# NOTE: to be run from the top directory
version: "3"
services:
  iam-db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./var/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iam
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=hdig8g4g49htuhe

  iam-object-store:
    image: minio/minio:RELEASE.2020-06-03T22-13-49Z
    ports:
      - "11101:9000"
    volumes:
      - ./var/object-store:/data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data

  monolith:
    build:
      context: $PWD
      dockerfile: $PWD/examples/monolith/Dockerfile
    restart: on-failure
    depends_on:
      - iam-db
      - iam-object-store
    ports:
      - 8080:8080
    volumes:
      # To simulate secrets in Swarm mode
      - ./secrets:/run/secrets
    env_file:
      - ./secrets/config.env
    environment:
      - LOG_PRETTY=true
