# NOTE: to be run from the top directory

version: "3"

services:
  iam-db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./iam/var/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iam
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=hdig8g4g49htuhe

  iam-object-store:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - "11101:9000"
    volumes:
      - ./iam/var/object-store:/data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data

  iam-server:
    build:
      context: ../..
      dockerfile: ./apps/iam-standalone-server/iam/Dockerfile
    restart: on-failure
    depends_on:
      - iam-db
      - iam-object-store
    ports:
      - "11111:8080"
      - "11121:9080"
      - "11131:50051"
    volumes:
      # To simulate secrets in Swarm mode
      - ./iam/etc/secrets:/run/secrets
      - ./iam/var/local-object-store:/object-store-data
    env_file:
      - ./iam/etc/secrets/config.env
    environment:
      - REALM_NAME=Kadisoka Standalone IAM Server
      - IAM_GRPC_ENABLED=true
      - IAM_HTTP_BASE_PATH=/
      - IAM_REST_CANONICAL_BASE_URL=http://localhost:11121/rest/v1/
      - LOG_LEVEL=debug
      - LOG_PRETTY=true
