# NOTE: to be run from the top directory

version: "3"

services:
  iam-db:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./var/iam-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iam
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=hdig8g4g49htuhe

  iam-object-store:
    image: minio/minio:latest
    ports:
      - "11101:9000"
    volumes:
      - ./var/iam-object-store:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data

  iam-server:
    build:
      context: ../..
      dockerfile: ./iam/iam-server/Dockerfile
    restart: on-failure
    depends_on:
      - iam-db
      - iam-object-store
    ports:
      - "11111:8080"
      - "11121:9080"
      - "11131:50051"
    volumes:
      # To simulate secrets in Swarm mode
      - ./etc/iam-server/secrets:/run/secrets:ro
      - ./var/iam-server/local-object-store:/object-store-data
    env_file:
      - ./etc/iam-server/secrets/config.env
    environment:
      - REALM_NAME=Kadisoka Standalone IAM Server
      - IAM_GRPC_ENABLED=true
      - IAM_HTTP_BASE_PATH=/
      - IAM_REST_CANONICAL_BASE_URL=http://localhost:11121/rest/v1/
      - LOG_LEVEL=debug
      - LOG_PRETTY=true
